Config:
  #Do not change!
  ConfigVersion: "4"

  #if you want to use the global Bungee Mode turn this to true
  enableBungeecord: false

  #Prefix before every message
  prefix: ""
  #AnnounceMessage
  message: "%prefix% &3%player% &7found &3%amount% &7of &e%block% &7at &b%coordinates% &7in World &b%world%"

  #Interval to clear cached blocks in Minuted. Use 0 to deactivate.
  #If you use the cache clear feature it might happen, that a vein will be announced 2 times
  #The performance impact is minor
  cacheclear: 0

  #List of blocks which should be announced
  blocks:
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE

  discord:
    #if token is empty DiscordBot feature will be disabled
    #If Bungeecord is enabled you should turn this on in the Bungeecord config and turn off in Spigot config
    token: ""
    #the channel ID of the text channel where announcements will be posted
    channel: ""
    #the game the bot is playing
    playing: "Do not XRay"

  #Not yet implemented. Just a placeholder for upcoming Database Support
  DatabaseType: "MySQL"
  #Not yet implemented. Just a placeholder for upcoming Database Support
  MySQL:
    Host: "localhost"
    Port: "3306"
    Database: "Database"
    Username: "User"
    Password: "1234"
